AWSTemplateFormatVersion: 2010-09-09

Description: 'OpenTelemetry Example'

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wfercosta-deploy-lambda

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: '*'
          Action:
          - s3:*
          Resource: 
          - !Sub 'arn:aws:s3:::${Bucket}'
          - !Sub 'arn:aws:s3:::${Bucket}/*'
