AWSTemplateFormatVersion: 2010-09-09

Description: 'OpenTelemetry Example'

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: 
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-nodejs-amd64-ver-1-2-0:1
      FunctionName: fn-instrumented-open-telemetry
      Description: Instrumented Lambda OpenTelemetry
      Handler: index.handler
      Runtime: nodejs12.x
      Role: !GetAtt Role.Arn
      Timeout: 300
      Code: ../app
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
