AWSTemplateFormatVersion: 2010-09-09

Description: 'OpenTelemetry Example'

Resources:
  # Role:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service: 
  #           - lambda.amazonaws.comm
  #         Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #     - arn:aws:iam::aws:policy/service role/AWSLambdaBasicExecutionRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fn-instrumented-open-telemetry
      Description: Instrumented Lambda OpenTelemetry
      Handler: index.handler
      Runtime: nodejs12.x
      Role: !GetAtt Role.Arn
      Timeout: 300
      Code: ../app
