AWSTemplateFormatVersion: 2010-09-09

Description: 'OpenTelemetry Example'

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-deploy-artifacts

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: '*'
          Action:
          - s3:*
          Resource: 
          - !Join ['', arn:aws:s3:::, !Ref Bucket]
          - !Join ['', arn:aws:s3:::, !Ref Bucket, '/*']

  Role:
    Type: AWS:IAM:Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2010-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.comm
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service role/AWSLambdaBasicExecutionRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fn-instrumented-open-telemetry
      Description: Instrumented Lambda OpenTelemetry
      Handler: index.handler
      Runtime: nodejs12.x
      Role: !GetAtt Role.Arn
      Timeout: 300
      Code: ../app
