name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
        working-directory: app 
      - name: deploy
        working-directory: infra
        run: |
          aws cloudformation package \
            --template-file main.yaml \
            --s3-bucket lambda-deploy-artifacts \
            --s3-prefix fn-instrumented-opt-deploy \
            --output-template-file main-packaged.yaml
          aws cloudformation deploy \
            --template-file main-packaged.yaml \
            --stack-name demo-open-telemetry \
            --region us-east-1 \
            --capabilities CAPABILITY_IAM